"""replace people_counts with crossing_events

Revision ID: 8f0b0db69afa
Revises: d12f2f064cde
Create Date: 2026-02-21 17:10:43.036407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f0b0db69afa'
down_revision: Union[str, None] = 'd12f2f064cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crossing_events_camera_id'), 'crossing_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_crossing_events_timestamp'), 'crossing_events', ['timestamp'], unique=False)
    op.drop_index('ix_people_counts_camera_id', table_name='people_counts')
    op.drop_index('ix_people_counts_timestamp', table_name='people_counts')
    op.drop_table('people_counts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_counts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('people_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_counts_pkey')
    )
    op.create_index('ix_people_counts_timestamp', 'people_counts', ['timestamp'], unique=False)
    op.create_index('ix_people_counts_camera_id', 'people_counts', ['camera_id'], unique=False)
    op.drop_index(op.f('ix_crossing_events_timestamp'), table_name='crossing_events')
    op.drop_index(op.f('ix_crossing_events_camera_id'), table_name='crossing_events')
    op.drop_table('crossing_events')
    # ### end Alembic commands ###
