"""create people_counts table

Revision ID: d12f2f064cde
Revises: 
Create Date: 2026-02-21 16:19:32.412344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12f2f064cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_counts_camera_id'), 'people_counts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_people_counts_timestamp'), 'people_counts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_counts_timestamp'), table_name='people_counts')
    op.drop_index(op.f('ix_people_counts_camera_id'), table_name='people_counts')
    op.drop_table('people_counts')
    # ### end Alembic commands ###
